### ISSUE TITLE
Mutación — Crear User Ticket

### ISSUE THREAD

**Issue by fforres** [JSConfCL/gql_api#26]
Un `userTicket` es la instancia de un ticket. Es la entrada de un usuario a un evento, la entidad que realmente se va a validar/quemar cuando el usuario atienda el evento. 
Un `userTicket` esta a asociado a un "TICKET" .

-------------------

- Esta mutación tiene que intentar crear un "userTicket"
- La manera de asociar un "userTicket" a un TICKET es mediante la tabla user_tickets.
- Un TICKET esta asociado a un evento
	- (PS: Un evento esta asociado a al menos una comunidad)
- La mutación debe recibir un TicketID además de los valores del rsvp.
- 

Permisos/validaciones
- El usuario existe.
- El evento esta activo.
- El ticket esta activo.

---------------------

## TODO:
- [ ] Una persona puede reservar tickets gratis.

## Extras
- [ ] Hay un límite de tickets por persona.
- [ ] Una persona puede reservar tickets pagados. (AKA, flujo de compra)
- [ ] Idempotency key

**Comment by fforres** [comment]
La mutación debería recibir solo:

- TicketTemplateId (Para saber a que `Ticket` esta asociado el `UserTicket`)
- UserID (Esto va por defecto, porque el usuario es el que ejecuta la acción)


SI miramos acá https://github.com/JSConfCL/gql_api/blob/main/src/datasources/db/userTickets.ts#L7-L31, estos son los datos que necesitaríamos obtener de **algun** lado antes de poder crear el `userTicket`

(Si esos datos vienen desde el request, o los sacamos de otra tabla, es la otra discusión 😆 )

Pero cuento corto, si miramos el esquema en ese link, hay harto que está "not null" pero hay harto que está con valores por defecto, con el `.default()` 🙏 



### Ahi entran las reglas de negocio, por ejemplo:

---------------------

Cuando la mutación este creando un `userTicket`, en el campo `approvalStatus` podemos poner "approved" o "pending". 
Para decidir, tenemos que mirar al `Ticket`,  y poner "approved" solo si el `Ticket` tiene `requiresApproval: false`.


-----------------------

Si vamos a crear un userTicket, tenemos que revisar que el `Ticket` tenga `status: active` (cuando el `Ticket` está en `inactive` es si por ejemplo, un evento esta pausado, onda si el ticket es un early bird, y lo queremos pausar por 2 días por ejemplo)

-----------------------

Si vamos a crear un userTicket, tenemos que revisar que el `Evento` tenga `status: active` (Igual que el anterior, es si el evento por ejemplo, esta pausado.)


También revisar si la fecha actual, es más grande que `endDateTime` del evento, eso quiere decir q el evento ya terminó.

----------------------

Lo otro, solo es posible crear un ticket, si hay suficientes "tickets disponibles"

Para hacer esto tenemos que:
- Contar la cantidad de `userTickets` que sean `status: active`, `approvalStatus: approved` de un ticket.
- Ver el campo `quantity` en el `Ticket`.
- Ver el campo `maxAttendees` en el `Event`

Confirmar que la suma de userTickets es menor que `maxAttendees` y que `quantity`

**Comment by fforres** [comment]
@Benjvvp es caleta de logica, derepente deberíamos dividirlo en un par de sub-tickets

**Comment by fforres** [comment]
"Finalizado" acá https://github.com/JSConfCL/gql_api/pull/135
